---
version: '2'
services:
  influxdb:
    image: influxdb:latest
    hostname: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DB: akka_streams
    volumes:
      - ./influxdb:/var/lib/influxdb
    command: influxd

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
