---
version: '2'
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    hostname: prometheus
    depends_on: 
      - akka-streams-app
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090"

  akka-streams-app:
    image: akka-streams-metrics
    hostname: akka-streams-app
    ports:
      - "8080:8080"
      - "9095:9095"

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
