---
version: '2'
services:
  influxdb:
    image: influxdb:latest
    hostname: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DB: akka_streams
    command: influxd 
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
  example:
    image: akka-streams-metrics:1.0-SNAPSHOT
    depends_on:
      - influxdb
      - grafana
    ports:
      - "8080:8080"
    environment:
      HTTP_INTERFACE: 0.0.0.0
      PORT: 8080

